# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('dg', 'Digital'), ('ps', 'Physical')], default='dg', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('favorite', models.BooleanField(default=False)),
                ('n_songs', models.IntegerField(max_length=3)),
                ('a_date', models.DateTimeField(verbose_name='album date')),
                ('c_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('albums', models.ManyToManyField(to='myrepository.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_date', models.DateTimeField(verbose_name='date lent')),
                ('c_date', models.DateTimeField(verbose_name='date created')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Genre'),
        ),
    ]
