# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='n_songs',
            field=models.IntegerField(),
        ),
    ]
