# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0003_remove_album_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
