# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0005_auto_20170416_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('c_date', models.DateTimeField(verbose_name='date created')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Album', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('c_date', models.DateTimeField(verbose_name='date created')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Album', unique=True)),
            ],
        ),
    ]
