# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0006_artist_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Album'),
        ),
    ]
