# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0007_auto_20170416_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrepository.Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
