# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0008_auto_20170416_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='id',
        ),
        migrations.AlterField(
            model_name='lending',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myrepository.Album'),
        ),
    ]
