# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrepository', '0010_auto_20170416_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='myrepository.Genre'),
        ),
    ]
